"""Try importing all main modules to detect circular imports / runtime errors."""
from __future__ import annotations

import importlib
import traceback

mods = [
    "core",
    "core.base",
    "core.browser_runner",
    "core.config_store",
    "core.models",
    "core.paths",
    "core.project_ui",
    "core.registry",
    "core.step_debug",
    "core.task_runner",
    "captcha.base",
    "captcha.cloudflare.captcharun",
    "captcha.cloudflare.captcharun.provider",
    "captcha.cloudflare.flaresolverr",
    "captcha.cloudflare.flaresolverr.provider",
    "captcha.cloudflare.flaresolverr.utils",
    "captcha.hcaptcha.captcharun",
    "captcha.hcaptcha.captcharun.provider",
    "captcha.turnstile.browser_manual",
    "captcha.turnstile.browser_manual.provider",
    "captcha.turnstile.capsolver",
    "captcha.turnstile.capsolver.provider",
    "captcha.turnstile.captcharun",
    "captcha.turnstile.captcharun.provider",
    "captcha.turnstile.yescaptcha",
    "captcha.turnstile.yescaptcha.provider",
    "mailsys.base",
    "mailsys.cloudflare_worker",
    "mailsys.cloudflare_worker.provider",
    "mailsys.mailnest",
    "mailsys.mailnest.provider",
    "mailsys.tempmail",
    "mailsys.tempmail.provider",
    "mailsys.xunmail",
    "mailsys.xunmail.provider",
    "proxy.base",
    "proxy.clash",
    "proxy.clash.provider",
    "proxy.http_proxy",
    "proxy.http_proxy.provider",
    "proxy.none",
    "proxy.none.provider",
    "proxy.socks5",
    "proxy.socks5.provider",
    "proxy.socks5.forwarder",
    "proxy.socks5.http_forwarder",
    "export.file",
    "export.file.provider",
    "export.grok2api",
    "export.grok2api.provider",
    "export.sub2api",
    "export.sub2api.provider",
    "verify.nvidia_api",
    "verify.nvidia_api.provider",
    "projects.chatgpt_register.project",
    "projects.chatgpt_register.steps",
    "projects.chatgpt_register.steps._browser",
    "projects.chatgpt_register.steps._challenge",
    "projects.chatgpt_register.steps._http_engine",
    "projects.chatgpt_register.steps._sentinel",
    "projects.chatgpt_register.steps.step01_open_login",
    "projects.chatgpt_register.steps.step02_submit_email",
    "projects.chatgpt_register.steps.step03_verify_email",
    "projects.chatgpt_register.steps.step04_complete_profile",
    "projects.chatgpt_register.steps.step05_extract_session",
    "projects.grok_register.project",
    "projects.grok_register.steps",
    "projects.grok_register.steps._lite_engine",
    "projects.nvidia_build.project",
    "projects.nvidia_build.steps",
    "projects.nvidia_build.steps._rpa",
    "projects.nvidia_build.steps._flow",
    "projects.nvidia_build.steps._http_engine",
    "projects.nvidia_build.steps._http_engine_v2",
    "projects.nvidia_build.steps._hybrid_engine",
    "projects.nvidia_build.steps.step01_open_signin",
    "projects.nvidia_build.steps.step02_accept_cookies",
    "projects.nvidia_build.steps.step03_email_next",
    "projects.nvidia_build.steps.step06_input_password",
    "projects.nvidia_build.steps.step07_confirm_password",
    "projects.nvidia_build.steps.step08_check_agreement",
    "projects.nvidia_build.steps.step09_solve_captcha",
    "projects.nvidia_build.steps.step10_inject_token",
    "projects.nvidia_build.steps.step11_create_account",
    "projects.nvidia_build.steps.step12_verify_email",
    "projects.nvidia_build.steps.step13_fetch_apikey",
]

fail = 0
for m in mods:
    try:
        importlib.import_module(m)
        print(f"OK   {m}")
    except Exception as e:
        print(f"FAIL {m}: {type(e).__name__}: {e}")
        traceback.print_exc()
        fail += 1
print(f"--- {fail} failures / {len(mods)} modules ---")
